language: python

python:
- "3.7-dev"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

script:
- python3 -m unittest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
    python: '3.7'
